source("LoadData.R")
png(filename = "Plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(subdata$DateTime, subdata$Global_active_power, type="n", ylab = "Global Active Power (kilowatts)", xlab="")
lines(subdata$DateTime, subdata$Global_active_power, type="l" )
plot(subdata$DateTime, subdata$Voltage, type="n", ylab = "Voltage", xlab="DateTime")
lines(subdata$DateTime, subdata$Voltage, type="l" )
plot(subdata$DateTime, subdata$Sub_metering_1, type="n", ylab = "Energy Sub Metering", xlab="")
lines(subdata$DateTime, subdata$Sub_metering_1, type="l", col = "red" )
lines(subdata$DateTime, subdata$Sub_metering_2, type="l" , col = "orange")
lines(subdata$DateTime, subdata$Sub_metering_3, type="l", col = "blue" )
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("red", "orange", "blue"), lty=1:1 , cex=0.8 )
plot(subdata$DateTime, subdata$Global_reactive_power, type="n", ylab = "Global Reactive Power (kilowatts)", xlab="DateTime")
lines(subdata$DateTime, subdata$Global_reactive_power, type="l" )
dev.off()